import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Al Badmari
 */
public class BookOperation extends javax.swing.JFrame {

    /**
     * Creates new form BookOperation
     */
    public BookOperation() {
        initComponents();
        table_update();
    }
    
     Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void search(String str){
        DefaultTableModel model = (DefaultTableModel) tableBook.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        tableBook.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     public void table_update()
        {
            
            int c;
            
            
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/gestionbibliotheque?useSSL=true","root","");
            pst = con.prepareStatement("SELECT * FROM livre");
            
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            
            c = rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)tableBook.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int i=1; i<=c; i++)
                {
                    v2.add(rs.getString("CodeBar"));
                    v2.add(rs.getString("Nom"));
                    v2.add(rs.getString("DateAcquisition"));
                    v2.add(rs.getString("DatePrevue"));
                    v2.add(rs.getString("Sale"));
                    v2.add(rs.getString("ID_Librairie"));
                }
                df.addRow(v2);
            }
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookOperation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BookOperation.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableBook = new javax.swing.JTable();
        btnPremier = new javax.swing.JButton();
        btnPrecedent = new javax.swing.JButton();
        btnSuivant = new javax.swing.JButton();
        btnDernier = new javax.swing.JButton();
        btnRetour = new javax.swing.JButton();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textRechercher = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textIdLibrary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textBack = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textAcquisition = new javax.swing.JTextField();
        javax.swing.JButton jButton3 = new javax.swing.JButton();
        javax.swing.JButton btnSup = new javax.swing.JButton();
        comboSalle = new javax.swing.JComboBox<>();
        btnAjt = new javax.swing.JButton();
        javax.swing.JButton btnModif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code Bar", "Nom", "Date_Acquisition", "Date Retour", "Salle", "ID Librairie"
            }
        ));
        tableBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBook);

        btnPremier.setBackground(new java.awt.Color(0, 102, 153));
        btnPremier.setText("<< Premier");
        btnPremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremierActionPerformed(evt);
            }
        });

        btnPrecedent.setBackground(new java.awt.Color(0, 102, 153));
        btnPrecedent.setText("< Precedent");
        btnPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedentActionPerformed(evt);
            }
        });

        btnSuivant.setBackground(new java.awt.Color(0, 102, 153));
        btnSuivant.setText("Suivant >");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });

        btnDernier.setBackground(new java.awt.Color(0, 102, 153));
        btnDernier.setText("Dernier >>");
        btnDernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDernierActionPerformed(evt);
            }
        });

        btnRetour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back(1).png"))); // NOI18N
        btnRetour.setText("Retour");
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));

        textRechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textRechercherKeyReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jLabel1.setText("Entrez une Chaine");

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Nom");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Date d'acquisition");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Salle");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("ID de Librairie");

        textCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Code Bar");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Date de retour");

        jButton3.setText("Actualiser");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnSup.setBackground(new java.awt.Color(204, 0, 0));
        btnSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        btnSup.setText("Supprimer");
        btnSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupActionPerformed(evt);
            }
        });

        comboSalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salle 1", "Salle 2", "Salle 3", "Salle 4", "Salle 5", "Salle 6" }));
        comboSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSalleActionPerformed(evt);
            }
        });

        btnAjt.setBackground(new java.awt.Color(0, 153, 0));
        btnAjt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAjt.setText("Ajouter");
        btnAjt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjtActionPerformed(evt);
            }
        });

        btnModif.setBackground(new java.awt.Color(0, 0, 204));
        btnModif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modify.png"))); // NOI18N
        btnModif.setText("Modifier");
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textAcquisition)
                            .addComponent(textName)
                            .addComponent(textBack)
                            .addComponent(textCode)
                            .addComponent(textIdLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(comboSalle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSup, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnModif)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjt))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModif)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(comboSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textIdLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textAcquisition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton3)))
                        .addGap(2, 2, 2)
                        .addComponent(btnSup)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPremier)
                        .addGap(32, 32, 32)
                        .addComponent(btnPrecedent)
                        .addGap(34, 34, 34)
                        .addComponent(btnSuivant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDernier))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRetour)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPremier)
                            .addComponent(btnPrecedent)
                            .addComponent(btnSuivant)
                            .addComponent(btnDernier))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRetour)
                .addGap(0, 57, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        textCode.setText("");
        textName.setText("");
        textAcquisition.setText("");
        textBack.setText("");
        comboSalle.setSelectedIndex(-1);
        textIdLibrary.setText("");
        textName.requestFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSalleActionPerformed

    private void textCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodeActionPerformed

    private void btnAjtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjtActionPerformed
        String CodeBar =  textCode.getText();
        String  nom =   textName.getText();
        String   dateAcqui=   textAcquisition.getText();
        String dateRetour = textBack.getText();
        String salle = comboSalle.getSelectedItem().toString();
        String IdLib =  textIdLibrary.getText();
        if(CodeBar.isEmpty() || nom.isEmpty() || dateAcqui.isEmpty() || dateRetour.isEmpty() || salle.isEmpty() || IdLib.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", "Ressayez SVP!",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel) tableBook.getModel();
            model.addRow(new Object []{ CodeBar, nom, dateAcqui, dateRetour, salle, IdLib});
        }
            

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/GestionBibliotheque?useSSL=true","root","");

            pst = con.prepareStatement("INSERT INTO Livre ( CodeBar, Nom, DateAcquisition, DatePrevue,Sale, ID_Librairie) VALUES ( ?,?,?,?,?,?)");

            pst.setString(1, CodeBar);
            pst.setString(2, nom);
            pst.setString(3, dateAcqui);
            pst.setString(4, dateRetour);
            pst.setString(5, salle);
            pst.setString(6, IdLib);

            pst.executeUpdate();
            table_update();

            JOptionPane.showMessageDialog(this, "Un livre a été ajouté avec succés !");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SubscriberOperation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SubscriberOperation.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_btnAjtActionPerformed

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed
        // TODO add your handling code here:
          DefaultTableModel d1 = (DefaultTableModel)tableBook.getModel();
        int selectIndex = tableBook.getSelectedRow();
        
        int dialogResult = JOptionPane.showConfirmDialog(this, "Voulez-vous modifier les info de ce livre ?", "Attention",JOptionPane.YES_NO_OPTION);
            
            if(dialogResult == JOptionPane.YES_OPTION)
            {
                
                try {
               
                 String id = d1.getValueAt(selectIndex, 0).toString();
                String CodeBar =  textCode.getText();
                String  nom =   textName.getText();
                String   dateAcqui=   textAcquisition.getText();
                 String dateRetour = textBack.getText();
                String salle = comboSalle.getSelectedItem().toString();
                String IdLib =  textIdLibrary.getText();
                
                 pst.executeUpdate();
                
            
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/gestionbibliotheque?useSSL=true","root","");
            
            
                pst = con.prepareStatement("UPDATE Abonne set Codebar = ?, Ville = ?, DateAcquisition = ?, DatePrevue =?, Sale = ? ,ID_Librairie = ? WHERE CodeBar = ? ");
                pst.setString(1, CodeBar);
                pst.setString(2, nom);
                pst.setString(3, dateAcqui);
                pst.setString(4, dateRetour);
                pst.setString(5, salle);
                pst.setString(6, IdLib);
                pst.setString(7, id);
            
                pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Livre Modifié !");
            table_update();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SubscriberOperation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SubscriberOperation.class.getName()).log(Level.SEVERE, null, ex);
        }
                
            }
        
    }//GEN-LAST:event_btnModifActionPerformed

    private void btnSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel)tableBook.getModel();
        int selectIndex = tableBook.getSelectedRow();

        String id = d1.getValueAt(selectIndex, 0).toString();

        int dialogResult = JOptionPane.showConfirmDialog(this, "Voulez-vous supprimer cet Abonné ?", "Attention",JOptionPane.YES_NO_OPTION);

        if(textCode.getText().equals("") || textName.getText().equals("") || textAcquisition.getText().equals("") || textBack.getText().equals("") ||  comboSalle.getSelectedItem().equals("") ||  textIdLibrary.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Veillez selectionner un Abonné, SVP !");
        }

        else if(dialogResult == JOptionPane.YES_OPTION)
        {
               int row = tableBook.getSelectedRow();
                DefaultTableModel model = (DefaultTableModel) tableBook.getModel();
            model.removeRow(row);
       try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/gestionbibliotheque?useSSL=true","root","");

                pst = con.prepareStatement("DELETE FROM Livre WHERE CodeBar = ?");

                pst.setString(1, id);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Livre supprimé avec Succès !");

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(IssueBook.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(IssueBook.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
      
    }//GEN-LAST:event_btnSupActionPerformed

    private void textRechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textRechercherKeyReleased
        
         String searchString = textRechercher.getText();
        search(searchString);
    }//GEN-LAST:event_textRechercherKeyReleased

    private void btnPremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremierActionPerformed
        Premier();
    }//GEN-LAST:event_btnPremierActionPerformed

    private void btnPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedentActionPerformed
        Precedent();
    }//GEN-LAST:event_btnPrecedentActionPerformed

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        suivant();
    }//GEN-LAST:event_btnSuivantActionPerformed

    private void btnDernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDernierActionPerformed
        dernier();
    }//GEN-LAST:event_btnDernierActionPerformed

    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
        this.hide();
        Home form = new Home();
        form.setVisible(true);
    }//GEN-LAST:event_btnRetourActionPerformed

    private void tableBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBookMouseClicked
        // TODO add your handling code here:
              DefaultTableModel mode = (DefaultTableModel)tableBook.getModel();
      int index = tableBook.getSelectedRow();
       textCode.setText(mode.getValueAt(index,0).toString());
        textName.setText(mode.getValueAt(index,1).toString());
        textAcquisition.setText(mode.getValueAt(index,2).toString());
        textBack.setText(mode.getValueAt(index,3).toString());
         comboSalle.setSelectedItem(mode.getValueAt(index, 4).toString());
        textIdLibrary.setText(mode.getValueAt(index,5).toString());
    }//GEN-LAST:event_tableBookMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BookOperation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjt;
    private javax.swing.JButton btnDernier;
    private javax.swing.JButton btnPrecedent;
    private javax.swing.JButton btnPremier;
    private javax.swing.JButton btnRetour;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JComboBox<String> comboSalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBook;
    private javax.swing.JTextField textAcquisition;
    private javax.swing.JTextField textBack;
    private javax.swing.JTextField textCode;
    private javax.swing.JTextField textIdLibrary;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textRechercher;
    // End of variables declaration//GEN-END:variables


//Defilement

int d;
    void defilemnet(int defiler){
        try{
            
           if(d == 0){
               btnPremier.setEnabled(false);
               btnPrecedent.setEnabled(false);
               
           }else{
               btnPremier.setEnabled(true);
               btnPrecedent.setEnabled(true);
       
           }
            if(d == tableBook.getRowCount()){
               btnSuivant.setEnabled(false);
               btnDernier.setEnabled(false);
               
           }else{
               btnSuivant.setEnabled(true);
               btnDernier.setEnabled(true);
       
           }
            textCode.setText(tableBook.getValueAt(defiler,0).toString());
            textName.setText(tableBook.getValueAt(defiler,1).toString());
            textAcquisition.setText(tableBook.getValueAt(defiler,2).toString());
            textBack.setText(tableBook.getValueAt(defiler,3).toString());
            comboSalle.setSelectedItem(tableBook.getValueAt(defiler,4).toString());
            textIdLibrary.setText(tableBook.getValueAt(defiler,5).toString());
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Defilement", JOptionPane.ERROR_MESSAGE);        }

}
    // boutton premier
    void Premier(){
        try{
            d=0;
            defilemnet(d);
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Premier", JOptionPane.ERROR_MESSAGE);        }
    }
    
     // boutton precedent
    void Precedent(){
        try{
            d--;
            defilemnet(d);
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Precedent", JOptionPane.ERROR_MESSAGE);        }
    }
    
    
    // boutton suivant
    void suivant(){
        try{
            d++;
            defilemnet(d);
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Suivant", JOptionPane.ERROR_MESSAGE);        }
    }
    
    
     // boutton Dernier
    void dernier(){
        try{
            d =tableBook.getRowCount()-1 ;
            defilemnet(d);
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Dernier", JOptionPane.ERROR_MESSAGE);        }
    }
    

    
}
